### PR TITLE
remodel contact us page

### PR DESCRIPTION
**Pull request by VonKiar**
refactor some html and css, added styling and little shadow effects. as well as placeholder for social media links.

### CODE REVIEW

**Review by Raikirieiei — APPROVED** [review]
The code is now easy to read.

**Review by PhumrapeeChaowanapricha — APPROVED** [review]
Nice!! The contact us page looks more attractive after refactoring.

**Review by Sahanon-P — APPROVED** [review]
It's work pretty fine. I already run it. Good job

**Review by Firstyfirst — APPROVED** [review]
Nice design. The user will like this templete

**Pull request merged**
