### PR TITLE
Improve navigation

### PR DESCRIPTION
**Pull request by Sahanon-P**
I've add the navigation to all the page we have. Please take a look.

### CODE REVIEW

**Comment by Sahanon-P** [comment]
I've find the defect in the search template so I fix it. Please take a look.

**Comment by Sahanon-P** [comment]
@Firstyfirst  Another thing I want you to do is after this branch merge can you set the alignment of the searched champion to be on the center?

**Review by PhumrapeeChaowanapricha — APPROVED** [review]

**Review by VonKiar — APPROVED** [review]
Shala Head shala~ nice 1

**Review by Raikirieiei — APPROVED** [review]
Ok now we can test navigation

**Pull request merged**
