### PR TITLE
add base_site.html and redesign index page

### PR DESCRIPTION
**Pull request by Firstyfirst**
I add the base_site.html for every page. All of you have to use this site. Another is redesign the index page and add the some feature to the new one.

### CODE REVIEW

**Comment by Sahanon-P** [comment]
I think you need to resolve the conflict first.

**Review by Raikirieiei — COMMENTED** [review]
Nice new design and base_site can be use later in other page.

**Review by Sahanon-P — APPROVED** [review]
I already check your template it's good that you use base_site to redice the duplicate html and css  and the other thing I see is you request some one to create the django for loop inside so I will take it as my duty.

**Review by Raikirieiei — APPROVED** [review]
Approved .Good base site

**Review by PhumrapeeChaowanapricha — APPROVED** [review]
new design and base_site is more suit to use in other pages.

**Pull request merged**
