### PR TITLE
Redesigned

### PR DESCRIPTION
**Pull request by VonKiar**
Redesigned for the final demo version, need more adjustment on create build and my build also the contact us might need some refactoring but the rest are almost done.

### CODE REVIEW

**Review by Raikirieiei — APPROVED** [review]
ok nice design.

**Review by Sahanon-P — CHANGES_REQUESTED** [review]
The return button is gone in detail page please fix.

**Review by PhumrapeeChaowanapricha — APPROVED** [review]
Design of each page is tidy and nice.

**Review by Firstyfirst — CHANGES_REQUESTED** [review]
The decoration is good. You should fix the position of return button in detail page and the footer on the base_site.html because you delete it from base_site.css. May be you forget to remove it.

**Comment by VonKiar** [comment]
I discussed with Sahanon and seems like the return button in detail page is not mandatory as we already have home page navigation, as for the footer I still have no idea what to put there so I will leave it blank for now.

**Pull request merged**
